### ISSUE TITLE
XMLHttpRequest cannot load

### ISSUE THREAD

**Issue by tmueller01** [derhansen/sf_banners#129]
Hi Torben,

more details :)

Display Error on TYPO3 6.2.19 - PHP 5.5.15

i want to setup the extension per typoscript. I make it this way:

lib.bannerTOP < plugin.tx_sfbanners.widgets.bannerWidget
lib.bannerTOP.settings.displayMode = allRandom
lib.bannerTOP.settings.startingPoint = 5 <- my own ID

But nothing is to see. With Firebug i see the error shown in the title.

**Comment by tmueller01** [comment]
Hi Torben,

problem solved. If i use baseURL without 'www' in TypoScript - the Banner will be shown.

**Comment by derhansen** [comment]
Thanks for your feedback. Glad to see it is working for you now!
