### ISSUE TITLE
Prevent Bannerlinks to generate new index-entry for the page

### ISSUE THREAD

**Issue by HorstBaumann** [derhansen/sf_banners#134]
T3 6.2.4
sf_banners 	0.6.2
indexed_search 	6.2.0

Pages with banners generate an additional entry in the indexed_search with the appended GET-parameters (like: &tx_sfbanners_pi1[action]=click&tx_sfbanners_pi1[banner]=1&tx_sfbanners_pi1[controller]=Banner) - which causes multiple search results for this page.

Can this be fixed via sf_banner or ist just a configuration for indexed_search to to made ?

thanks

**Comment by derhansen** [comment]
I don't know indexed_search very much, but maybe it is possible to prevent indexed search from crawling URLs with banner links.

**Comment by derhansen** [comment]
I'm closing the issue, since I think this can be handled by indexed_search
