### ISSUE TITLE
BannerPlacement is not defined

### ISSUE THREAD

**Issue by der-phillip** [derhansen/sf_banners#136]
Hello,

there is no banner displyed. But I have an error message in the console.

### Error
Uncaught ReferenceError: BannerPlacement is not defined(anonymous function) @ index.php?id=1:135
```
var banners = new BannerPlacement(1, 0, 9001, '36', '', 'all', 'banners-m2m3ztaxz', 'ba162672749c5fa97f2603c89254bdfb6b733a82');
```

### My TS
```
plugin.tx_sfbanners {	
	settings {
		displayMode = allRandom
		startingPoint = 36
	}
}

# Include JQuery if configured
[globalVar = LIT:1 = {$plugin.tx_sfbanners.settings.includeJquery}]
page.includeJS {
	bannerJQuery >
}
[end]

# Include banner JS
page.includeJS {
	htmlparser >
	postscribe >
	bannerJS >
}
page.includeJSFooterlibs {
	htmlparser = EXT:sf_banners/Resources/Public/Js/HtmlParser.js
	postscribe = EXT:sf_banners/Resources/Public/Js/Postscribe.js
	bannerJS = EXT:sf_banners/Resources/Public/Js/SfBanners.js
}

lib.mybanner < plugin.tx_sfbanners.widgets.bannerWidget
```

**Comment by derhansen** [comment]
Could you check, if "sf_banners/Resources/Public/Js/SfBanners.js" is in your FE output? This JavaScript lib must be included in your HTML output of your page.

**Comment by der-phillip** [comment]
Yes, at the bottom of the page. I send you a E-Mail with the link o the page.

**Comment by CWorksorg** [comment]
Sers,

you must write a little ViewHelper, so your inlineJS is added at the bottom of your page. Maybe something like that:

<?php
namespace DERHANSEN\SfBanners\ViewHelpers;

class InlineJsViewHelper extends \TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper {

    /**
     * @param mixed $pid
     * @param mixed $lang
     * @param mixed $typeNum
     * @param mixed $startingPoint
     * @param mixed $categories
     * @param mixed $displayMode
     * @param mixed $uniqueid
     * @param mixed $hmac
     */
    public function render( $pid, $lang, $typeNum, $startingPoint, $categories, $displayMode, $uniqueid, $hmac ) {
        $name = "banners-{$uniqueid}";
        $inlineJS = "var banners = new BannerPlacement({$pid}, {$lang}, {$typeNum}, '{$startingPoint}', '{$categories}', '{$displayMode}', 'banners-{$uniqueid}', '{$hmac}')";
        $GLOBALS['TSFE']->getPageRenderer()->addJsFooterInlineCode($name,$inlineJS,FALSE);
    }
}

After that your Banners are displayed.

**Comment by derhansen** [comment]
Hello,

I have refactored the way banners are defined. I've moved all JS includes to the page footer section and removed the dependency to JQuery for all inline JS code.

Would you mind testing the change #148 by checking out the development branch?

**Comment by derhansen** [comment]
I've tested the new implementation on TYPO3 6.2 and 7.x and it seem to work fine. Closing issue
