### ISSUE TITLE
Cache::initializeCachingFramework(); not working with 7.4

### ISSUE THREAD

**Issue by TrueType** [derhansen/sf_banners#137]
the class does not exist anymore. neither does the function. results in 

*Fatal error: Class 'TYPO3\CMS\Core\Cache\Cache' not found in /var/www/cms.de/typo3conf/ext/sf_banners/Classes/Controller/BannerController.php on line 92*

**Comment by derhansen** [comment]
Thanks for your report. I'll found this https://aimeos.org/tips/how-to-use-the-typo3-caching-framework-with-cache-groups/ blogpost from Aimeos which shows how the caching framework in 6.2 and 7+ should be used.

I'll provide a fixed version soon.

**Comment by derhansen** [comment]
@TrueType I have created a patch for this issue and pushed it to the development branch. I'll do some testing with TYPO3 7.x and see if I can release a new version which is compatible with TYPO3 6.2 and 7.x
