### ISSUE TITLE
[TASK] Test TYPO3 7.x compatibility

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_banners#140]

**Comment by TrueType** [comment]
You may want to drop any aliasclassmap before? If, there is a Tx_Extbase_Persistence_Typo3QuerySettings within BannerRepository. And a Tx_SfBanners_Domain_Model_Page within setup.txt

**Comment by derhansen** [comment]
Thanks, I'll keep this in mind during the cleanup!
