### ISSUE TITLE
jquery problem

### ISSUE THREAD

**Issue by tomkraw1** [derhansen/sf_banners#142]
I use sf_banners, yag and newsslider extensions on the site I work on. Each of those extensions use different version of the jQuery. So, I disabled including jQuery on each of them. I include jQuery in my root template once. Version the newest used in those extensions (1.11.0). 
I have banners placed on each pages of the site. But banners are shown only on those pages where yag or newsslider are used too.

**Comment by derhansen** [comment]
Did you include JQuery in the header section or the footer section of your page? I'm currently aware of an issue, that banners are not rendered, when JQuery is included in the header section and the JS code from sf_banners is rendered before the JQuery inclusion

**Comment by tomkraw1** [comment]
I included jquery at the top. In that way
<pre>
page.includeJS {
    jquery = http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js
    jquery.external = 1
    jquery.forceOnTop = 1
}
</pre>
I noticed that both NewsSlider and Yag are adding some JS libs at the end.
<pre>
<script src="/typo3conf/ext/newsslider/Resources/Public/Scripts/jquery.easing.js" type="text/javascript"></script>
									
									<script src="/typo3conf/ext/newsslider/Resources/Public/Scripts/jslidernews.js" type="text/javascript"></script>
									
									<script type="text/javascript">
/*<![CDATA[*/
/* JavaScript for News-Slider CE-16 */
jQuery(function(){jQuery('#lofslidecontent16').lofJSidernews( {sliderId:16,navPosition:'horizontal',interval:7000,navigatorHeight:15,navigatorWidth:25,duration:1000,pauseOnMouseOver:true,mainWidth:990});});

/*]]>*/
</script>
</pre>

and

<pre>
<script src="/typo3conf/ext/yag/Resources/Public/Js/MagnificPopup/dist/jquery.magnific-popup.min.js" type="text/javascript"></script>
						
						<script src="/typo3conf/ext/yag/Resources/Public/Js/LightBox.js" type="text/javascript"></script>
</pre>

But when I change my TS to :
<pre>
page.includeJSFooter {
    jquery = http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js
    jquery.external = 1
    jquery.forceOnTop = 1
}
</pre>

then jQuery is rendered at the bottom of the site but banners are not rendered.

**Comment by derhansen** [comment]
Any errors in the JavaScript console? Do you have a link to the site, so I can have a look at the FE HTML output?

**Comment by tomkraw1** [comment]
Banners should be rendered on every pages (at the end). See on address http://le0xow.e-kei.pl/ .

Main page contains "News slider" - banners are showing. Submenu Multimedia -> Galerie and deeper in albums banners are showing up again.

**Comment by derhansen** [comment]
Are you using absRefPrefix in your TYPO3 site? If yes, please use the development version (https://github.com/derhansen/sf_banners/tree/development), which contains a bugfix for the problem.

**Comment by tomkraw1** [comment]
Yes I use. Thanks this works!

**Comment by derhansen** [comment]
Thanks for your feedback. I'm currently working on the next release which will be available on TER soon.
