### ISSUE TITLE
Categories not respected

### ISSUE THREAD

**Issue by tomkraw1** [derhansen/sf_banners#150]
I have one storage folder for all banners.
I defined four categories but added two banners to one of them.
In my fluid page template I defined four places for banners. TS for all of them locks like this. 

<pre>
lib.bannerRight3 = COA
lib.bannerRight3 < plugin.tx_sfbanners.widgets.bannerWidget
lib.bannerRight3.settings {
	category = BocznyP3
	displayMode = random
}
</pre>

Now my banners are displayed in all four places. I expected banners from each category will be displayed in corresponding places.

**Comment by derhansen** [comment]
Hi, the ```settings.category``` setting must include the UID of the category, not the name. Could you try to insert the category UID instead? If you still got problems, please add some more details to this issue.

**Comment by tomkraw1** [comment]
Oh, right. It is in the manual ;-/
This solves my problem.
