### ISSUE TITLE
Issue on root page

### ISSUE THREAD

**Issue by adrienjacob** [derhansen/sf_banners#158]
Hello,

Thanks for this nice extension, really helpful... I just have a little bug when displaying the banners on the rootpage. I have the following error message :

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1467983513: ID parameter needs to be passed for the cHash calculation! As a temporary not recommended workaround, you can set $GLOBALS['TYPO3_CONF_VARS']['FE']['cHashIncludePageId'] to false to avoid this error. | RuntimeException thrown in file /var/www/typo3_src-7.6.11/typo3/sysext/frontend/Classes/Page/CacheHashCalculator.php in line 131.

I understand from recent security notices that cHashIncludePageId should remain true... So do you think there could be a work around ? It works nicely on other pages otherwise.
I run Typo3 7.6.11, with RealURL extension if it may matter.

Thanks !

**Comment by derhansen** [comment]
See https://forge.typo3.org/issues/78021

Should have been fixed with the TYPO3 core update, that came yesterday

**Comment by adrienjacob** [comment]
Indeed, thanks !
