### ISSUE TITLE
rel="nofollow"

### ISSUE THREAD

**Issue by TrueType** [derhansen/sf_banners#159]
Hi Torben,

I just had a customer asking me to configure rel="nofollow" links on the banners. Couldn't find that in the code. Has this subject ever been discussed here? It is years since I had to deal with nofollow the last time. I do not even know, if it is still relevant?

Henri

**Comment by derhansen** [comment]
Hi Henri,

I don't know if it is still relevant, but you can easily add the attribute in the Fluid template - see https://github.com/derhansen/sf_banners/blob/master/Resources/Private/Partials/Banner/ImageBanner.html#L5

Best regards
Torben

**Comment by derhansen** [comment]
I'll close this issue. If you think the rel="nofollow" should be added, feel free to contact me or reopen the issue.
