### ISSUE TITLE
Compatibility with v8 ?

### ISSUE THREAD

**Issue by adrienjacob** [derhansen/sf_banners#160]
Hi,

Are there any plans to make sf_banners compatible with the upcoming Typo3 v8 ? I just tried and it doesn't seem to work...

Thanks !

**Comment by derhansen** [comment]
Hi,

yes, I started yesterday with compatibility of my TYPO3 extensions for V8 and released a V8 compatible version of sf_yubikey. 

Next up is sf_banners, so you may expect the update before the release of TYPO3 8.7 LTS.

Regards,
Torben

**Comment by adrienjacob** [comment]
Great Torben, thanks a lot !

**Comment by derhansen** [comment]
Started working on the V8 version in this branch- https://github.com/derhansen/sf_banners/tree/v8_compatibility

**Comment by adrienjacob** [comment]
Thanks, I just tested it. After clearing the cache and running the DB analyser, it looks ok in the Frontend.
However, in the Backend, when I try to update / create banners for language "All", I get this error
`Argument 3 passed to TYPO3\CMS\Core\DataHandling\Localization\DataMapProcessor::synchronizeTranslationItem() must be of the type integer, null given`
In `TYPO3\CMS\Core\DataHandling\Localization\DataMapProcessor::synchronizeTranslationItem(TYPO3\CMS\Core\DataHandling\Localization\DataMapItem, array, NULL)`
It doesn't happen if I choose a particular language.

**Comment by derhansen** [comment]
I forgot to push the latest changes in the V8 Branch to GitHub. Now they are pushed and I also migrated the TCA

**Comment by adrienjacob** [comment]
Thanks @derhansen, works like a charm after pulling your latest changes, and also pulling the latest changes on the core (I'm using 8.7.0-dev).

**Comment by derhansen** [comment]
Thanks for your feedback. I will publish the new version to TER soon
