### ISSUE TITLE
Data Structure Error

### ISSUE THREAD

**Issue by rosimittermeier** [derhansen/sf_banners#162]
Hi, implementing a content element with your banner-extension I get:

Data structure error: The file "EXT:sf_banners/Configuration/FlexForms/Flexform_plugin.xml" in ds-array key "sfbanners_pi1,list" was not found ("/home/www/sites/2017_db8/typo3conf/ext/sf_banners/Configuration/FlexForms/Flexform_plugin.xml")

I installed the extension from TER. I added static template. I added a data-sys-folder (with banners and categories). I added as a content element on a page the general plugin and then selected your plugin. Then the error appeared. I cannot edit the content element anymore.

screenshot:
![clipboard01](https://cloud.githubusercontent.com/assets/13799805/23854735/090413b0-07f3-11e7-8ecb-0e9c49e1892f.png)

greetings
hans

**Comment by derhansen** [comment]
I can't reproduce the error. Did you flush all caches in the install tool? Can you try to reinstall the extension from TER?

**Comment by rosimittermeier** [comment]
(1) all caches had been deleted
(2) I deinstalled and reinstalled the extension after deleting sys-folder etc.
(3) the same error as before. Here is the protocol-view error message:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1440506893: Data structure error: The file "EXT:sf_banners/Configuration/FlexForms/Flexform_plugin.xml" in ds-array key "sfbanners_pi1,list" was not found ("/home/www/sites/avminor/typo3conf/ext/sf_banners/Configuration/FlexForms/Flexform_plugin.xml") | UnexpectedValueException thrown in file /home/www/sites/typo3_src-7.6.16/typo3/sysext/backend/Classes/Form/FormDataProvider/TcaFlexFetch.php in line 70. Requested URL: https://ethik.philosovieth.de/typo3/index.php?route=%2Frecord%2Fedit&token=c0e0c791d1c0e1219f7c3f2c3e018d2058e16020&edit[tt_content][5]=new&defVals[tt_content][colPos]=0&defVals[tt_content][sys_language_uid]=0&defVals[tt_content][CType]=list&returnUrl=%2Ftypo3%2Findex.php%3FM%3Dweb_layout%26moduleToken%3Dfb931a0efea9e63e037173a9bfa0c4d2c3b35577%26id%3D5%26 

(4) I tried with activated and deactivated realurl-extension
(5) It is the same in two different and independent typo3-7.6.16 environments each with realurl, bootstrap_package.

**Comment by rosimittermeier** [comment]
(6) and the frontend displays error-message:

Oops, an error occurred! Code: 20170317123007f5a3601c There must be at least one constraint or a non-empty array of constraints given. exception code:1268056288 file:/typo3/sysext/extbase/Classes/Persistence/Generic/Query.php line:417 fh_debug trace: file: /typo3conf/ext/sf_banners/Classes/Domain/Repository/BannerRepository.php" line:82 function:logicalAnd file: /typo3conf/ext/sf_banners/Classes/Controller/BannerController.php" line:172 function:findDemanded file: " line: function:getBannersAction file: /typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php" line:283 function:call_user_func_array file: /typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php" line:176 function:callActionMethod file: /typo3/sysext/extbase/Classes/Mvc/Dispatcher.php" line:86 function:processRequest file: /typo3/sysext/extbase/Classes/Mvc/Web/FrontendRequestHandler.php" line:69 function:dispatch file: /typo3/sysext/extbase/Classes/Core/Bootstrap.php" line:206 function:handleRequest

**Comment by derhansen** [comment]
I again tried to reproduce the problem without success. Did a fresh composer installation of TYPO3 7.6.16 with bootstrap_package and sf_banners and the problem does not appear.

Could you check, if the file `/home/www/sites/2017_db8/typo3conf/ext/sf_banners/Configuration/FlexForms/Flexform_plugin.xml` exists on your server

**Comment by rosimittermeier** [comment]
thanks! the file flexform_plugin.xml is existing.

I myself installed a new typo3 7.6.16 instance. 
I added realurl, bootstrap_package and sf_banners extensions. 
I loaded German language. 
I created a new website-template. 
integrated static templates (bootstrap, sf-banners). 
created website-languages on id=0. 

Then I added a sysfolder and added some sf-banner-files and sf-banner-categories.
And I added on the root-page a content element from a plugin. 
then I chose the banner-plugin 
and said yes to changing the formular. 
... then the backend-page collapses (as you see in my first message). and the frontend has an oops.

so perhaps, if I made no mistake, it should have something to do with the server (webhoster).
thanks for your answers and troubles.
hans

**Comment by rosimittermeier** [comment]
perhaps this might be helpful:

the apache error log file offers a report, when adding a common-plugin and choosing banner:

[Sat Mar 18 17:18:53 2017] [error] [client 84.186.190.226] File does not exist: /home/www/test_db11/sitedaten/typo3/sysext/images, referer: https://test.xxx.de/typo3temp/compressor/merged-49bcaa37d60e3e2519917e8fb18da230-2af12049b5648ea7042d70f902eb761d.css?1489849870

the css-file exists
there are some sf-banner definitions in it.
but the error has to do with: typo3/sysext/images. there are some information in the css:

background-image:url('../../typo3/sysext/images/backgrounds/button-hover.png');
background:transparent url('../../typo3/sysext/images/spinner/d5d5d5.gif') no-repeat 0 3px;
.typo3-pagetree-deletionDropZone-proxyOver .x-dd-drop-icon{background-image:url('../../typo3/sysext/images/icons/actions/edit-delete.png');

neither the path /images/... does exist nor the subpaths or png-files.

So, whatever the cause might be, I suppose that sf-banner has nothing to do with my problems.

thanks again!
hans

**Comment by derhansen** [comment]
Sorry for the trouble - a user reported the same problem along with the bugfix. Version 2.0.1 will be released on TER in a couple of minutes.

**Comment by rosimittermeier** [comment]
hi, it works! but perhaps you could add some details for the user in the manual: I added in the sysfolder the banner-imgages. What about the "categories"? If I add categories, the content element does not work. If I delete them it works. I would expect, that I have a list of images and a list of categories -- then I can choose for each image one or more categories. And at least the content-element chooses randomly (or so) images of the categories. presumably my assumptions are wrong. but that's what I would expect. And, additionally: The banner in the frontend should perhaps have the css-options "width: 100%, height:100%" and/or "overflow:hidden;" All in all its a really nice and useful feature for typo3-frontends.   28.03.2017, 18:55, "Torben Hansen" <notifications@github.com>:Sorry for the trouble - a user reported the same problem along with the bugfix. Version 2.0.1 will be released on TER in a couple of minutes.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
