### ISSUE TITLE
Wrong renderType for category in banner TCA

### ISSUE THREAD

**Issue by christian-fries** [derhansen/sf_banners#166]
The renderType of the column _category_ is currently defined as _tree_ which is no valid renderType. It should be _selectTree_ for TYPO3 7.6+.

Editing a banner shows the message "Unknown type: select"
![bildschirmfoto 2017-04-17 um 11 02 42](https://cloud.githubusercontent.com/assets/852644/25084683/2c569244-235e-11e7-9561-e4a0253bc3ce.png)

**Comment by christian-fries** [comment]
The same issue applies to the column _parent_ in category TCA.

**Comment by derhansen** [comment]
Bugfixed version 2.0.3 has been uploaded to TER
