### ISSUE TITLE
[FEATURE] Support FAL for images

### ISSUE THREAD

**Issue by christian-fries** [derhansen/sf_banners#167]
With TYPO3 CMS 7.6.18 and sf_banners 2.0.3 it's not possible to use the same image for more than one banner. Additionally, when an image is selected from the file list and the image is replaced in the file list module later, the banner won't be replaced. It would be a big improvement if sf_banners would use FAL for images.

**Comment by derhansen** [comment]
PR for the feature has been merged to the development branch

**Comment by derhansen** [comment]
New release with FAL support available today.
