### ISSUE TITLE
[FEATURE] Add FAL migration script

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_banners#171]

**Comment by derhansen** [comment]
Wont have time :-(

**Comment by claude27** [comment]
I hereby provide you a script with which I migrated the images, see attached tar.gz file. Only I forgot to that the title, alias and link must also be migrated which I then made manually, so the script isn't completed and but must be extended.
[extkey.tar.gz](https://github.com/derhansen/sf_banners/files/1625440/extkey.tar.gz)
