### ISSUE TITLE
Update typo3 7.6 ---> 8.7

### ISSUE THREAD

**Issue by rosimittermeier** [derhansen/sf_banners#173]
there are problems with the extension in 8.7. it seems to be incompatible with 8.7 (see screenshots).

![sf_banners_tca_problems 1](https://user-images.githubusercontent.com/13799805/29944003-f85dc508-8e9b-11e7-9e65-169710302850.png)

![sf_banners_tca_problems 2](https://user-images.githubusercontent.com/13799805/29944004-f85e5b1c-8e9b-11e7-8594-4498ca1828ab.png)

![sf_banners_tca_problems 3](https://user-images.githubusercontent.com/13799805/29944005-f8611032-8e9b-11e7-9544-df27ae340309.png)

**Comment by derhansen** [comment]
Could you please specify what problems you have with the extension in TYPO3 8.7.

You screenshots shows information about TCA migrations regarding TYPO3 8.7, which IMO all are none critical and should not produce any problems. Due to, that the extension still has TYPO3 7.6 compatibility, those TCA changes can't be applied to sf_banners at the moment.

**Comment by rosimittermeier** [comment]
thanks! until now I did not recognize no problems. only these non-critical diagnoses of typo3. thanks, and bye 01.09.2017, 19:19, "Torben Hansen" <notifications@github.com>:Could you please specify what problems you have with the extension in TYPO3 8.7.You screenshots shows information about TCA migrations regarding TYPO3 8.7, which IMO all are none critical and should not produce any problems. Due to, that the extension still has TYPO3 7.6 compatibility, those TCA changes can't be applied to sf_banners at the moment.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by derhansen** [comment]
Thanks for your feedback. I'm closing this issue. Feel free to create a new issue, if you should find a new issue.
