### ISSUE TITLE
[!!!][TASK] Use FAL images by default

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_banners#175]

**Comment by bench-artwork** [comment]
Using the latest development branch and the default FAL option the link field is missing and already saved links aren't rendered in frontend! Some TCA and fluid seems to be wrong.

**Comment by derhansen** [comment]
Sorry, my fault. I did'nt notice the missing Link-Field for FAL assets. I've updated the TCA now. Could you please recheck the latest commit?

**Comment by bench-artwork** [comment]
No worries! Does work again! Thx for your blazing fast fix!
BTW why not remove the old image config as long min. requirement is TYPO3 7?

**Comment by derhansen** [comment]
Old config will be removed one major release later, so people still have the possibility to migrate images from the old config.
