### ISSUE TITLE
[!!!][FEATURE] Categories based on sys_category

### ISSUE THREAD

**Issue by bench-artwork** [derhansen/sf_banners#178]
as the title said, why not using sys_category for managing categories!

**Comment by derhansen** [comment]
Main reason is, because the initial version of the extension was developed before sys_category did exist. 

I never had the time to switch to sys_categories for sf_banners. Should be no huge task, so lets keep the issue open for the next release

**Comment by claude27** [comment]
by the way, for a migration script (when TCA and domain model are created) you could look at the address extension, where addressgroups have been migrated to sys_categories, or an older version of the tx_news extension, there has also been a migration script which could be adapted.

**Comment by derhansen** [comment]
Thanks for the hint. I have some code ready from one of my other extensions https://github.com/derhansen/sf_event_mgt/blob/master/class.ext_update.php#L140
