### ISSUE TITLE
Question about the banner interval

### ISSUE THREAD

**Issue by in-session** [derhansen/sf_banners#179]
Hi,

could you explain how the interval of single banner random is.
We included three images for the test and we have partially the following single random order (sorted by id):

1 | 1 | 2 | 3 | 2 | 2 | 1 | 1 | 2 | 3 | 1

It is possible to adjust the random?

Thanks in advance

**Comment by derhansen** [comment]
Hi, there is no interval for banner rotation in the extension.

You can either rotate one banner at a time random or display all banners in at once in a rendom order (see displayMode in the [manual](https://docs.typo3.org/typo3cms/extensions/sf_banners/Configuration/Reference/Index.html))

Hope this helps

**Comment by in-session** [comment]
Hi, thanks for the comment.
How exactly is the single random order calculated?

**Comment by derhansen** [comment]
The regular [query result](https://github.com/derhansen/sf_banners/blob/master/Classes/Persistence/RandomQueryResult.php) is randomized using the PHP [shuffle](http://php.net/manual/en/function.shuffle.php) function, which uses a pseudo random number generator.
