### ISSUE TITLE
Restrict fields for backend user groups

### ISSUE THREAD

**Issue by bench-artwork** [derhansen/sf_banners#180]
For our backend editors i would like to exclude some fields like clicks and impressions in the access list under be_groups. Currently there is only recursive, hidden, sys_language_uid, starttime and endtime.
Is it possible to extend this for all fields?

**Comment by bench-artwork** [comment]
ok got it, just set exclude = 1 in TCA. Any reason why not all fields are restrictable?

**Comment by derhansen** [comment]
No, not really :-) I will add exclude field option to all TCA fields in the next release
