### ISSUE TITLE
click tracking for html banners

### ISSUE THREAD

**Issue by bench-artwork** [derhansen/sf_banners#183]
how can i get click tracking for html banners (iframe)?
Any tips for best practices?

**Comment by derhansen** [comment]
Since an iframe includes content from a remote website, the remote website must also provide the click tracking.

**Comment by bench-artwork** [comment]
ok – why not generate the URL like with image banners and wrap the whole iframe with a link?
Could be done easily with css:

```
<f:if condition="{banner.html}">
    <div class="banner banner-{banner.uid}">
        <f:format.html parseFuncTSPath="">{banner.html}</f:format.html>
        <f:link.action action="click" arguments="{banner: banner}" target="{banner.linkTarget}" pageType="{settings.clickPageTypeNum}"></f:link.action>
    </div>
</f:if>

and 

.banner {
    position: relative;
}
.banner a {
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    text-decoration: none;
    z-index: 10;
    background-color: #FFF;
    opacity: 0;
}
```

**Comment by derhansen** [comment]
That could of course be a solution in your case, but I think this may break current functionality for many others using iframes as HTML banner, since links in the iframe would not be clickable any more.

I suggest, you override the default templates of the extension and implement your solution right away. If you have any problems, feel free to contact me.

**Comment by bench-artwork** [comment]
Thx for your fast reply;)

if you add a additional link field for html banners in TCA you could rendering this additional link only if there is a link. So no breaking of current functionalities in my opinion.

**Comment by derhansen** [comment]
I'm closing this issue now. If you need an extra fields, I suggest you extend the extension with the fields  you require.
