### ISSUE TITLE
[BUG] Language overlays not taken into account ?

### ISSUE THREAD

**Issue by adrienjacob** [derhansen/sf_banners#184]
With Typo3 8.7.19 and sf_banners 3.0.0, I can't seem to apply language overlays to banners... The default language keeps on being displayed. I tried many different variants of "Translation Behaviour" set to Custom value.
I tried disabling this line `$query->getQuerySettings()->setRespectSysLanguage(false);` in BannerRepository, but then it doesn't display anything, except on the default language page. I also tried some other query settings like `setlanguageOverlayMode`.
Thanks for your help.

**Comment by adrienjacob** [comment]
Ah, by the way I just upgraded to 3.0.1, problem remains (the TER didn't suggest the last version, as it's stated as not compatible with PHP 7.2, this could probably be changed, especially since the new LTS has a minimum requirement of PHP 7.2).

**Comment by derhansen** [comment]
I will investigate the issue, but this may sadly take some time, since workload is currently very heavy at the moment.

TER obviously does not suggest the version, since 3.0.1 is only tested and compatible with PHP 7.1 - Release for TYPO3 V9 will follow in approximately 12/2018 or 01/2019

**Comment by adrienjacob** [comment]
Dear @derhansen, thanks for getting back to me, but I tried your suggested fix and it didn't solve the problem. I don't understand your code enough to try and solve this 2 query issue...

**Comment by derhansen** [comment]
@adrienjacob Did you clear all caches after manually applying the suggested patch? Query results are cached using TYPO3 caching framework, so just adding the patch would not resolve the problem temporary.

**Comment by derhansen** [comment]
@adrienjacob I refactored the part of the extension now. Unit tests run fine and also my manual tests did succeed.

Could you test this branch https://github.com/derhansen/sf_banners/tree/v9_compatibility

**Comment by adrienjacob** [comment]
Well thanks, but it still doesn't work for me unfortunately. Funny thing is : if I disable (hide) the default language banner, but leave its translation enabled, the banner would show on the translated page, but using the image of the default language. So there seems to be some mixing up of the two languages.
I did use v9_compatibility branch (but on a v8 Typo3), and cleared all caches including opcode.

**Comment by derhansen** [comment]
I'm closing this issue now. Extension has been refactored. For TYPO3 8.7 it is still possible to use the old "image" field and for TYPO3 9.5 you can use FAL assets without any problems.

**Comment by adrienjacob** [comment]
Ah, thanks a lot @derhansen, I wasn't aware of this core bug :)
