### ISSUE TITLE
[BUG] External Link with FAL don't work

### ISSUE THREAD

**Issue by in-session** [derhansen/sf_banners#188]
Hi,

I installed your extension today and noticed that the link does not work with FAL settings. 
I assume that the link should be set using the FAL link {asset.originalResource.properties.link}?
The link does not open the URL of the banner, only the same page is displayed.

Typo3 9.5.1 + sf_banners | 4.0.0

Best Regards Christoph

**Comment by derhansen** [comment]
Fixed in Dev Branch

**Comment by in-session** [comment]
THX
