### ISSUE TITLE
No banners shown after update of TYPO3

### ISSUE THREAD

**Issue by JeppeDonslund** [derhansen/sf_banners#192]
I have updated my TYPO3 from 6 to 7.6, but now there are no banners shown.
I use sf_banners 3.0.1
Is it something about FAL images?

**Comment by derhansen** [comment]
Please see Release notes for Version 3 - https://github.com/derhansen/sf_banners/releases/tag/3.0.0

You have to activate old image support. Migration (sadly manual) to FAL is highly recommended

**Comment by derhansen** [comment]
Closing, no feedback
