### ISSUE TITLE
Cannot exclude Jquery

### ISSUE THREAD

**Issue by Balindil** [derhansen/sf_banners#193]
TYPO3 9.5.5 here. sf_banners 4.0.2

```
plugin {
  tx_sfbanners {
    settings {
      includeJquery = 0
    }
  }
}
```
does not work. There's still
`<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js" type="text/javascript"></script>` in source code.

**Comment by derhansen** [comment]
I can not reproduce the problem. Please make sure, that you set the `plugin.tx_sfbanners.settings.includeJquery = 0` setting in TypoScript constants and that you flush the TYPO3 cache afterwards. Then everything works as expected

**Comment by Balindil** [comment]
Thank you! Another try and it works now. Don't know the reason.
