### ISSUE TITLE
No banners are shown

### ISSUE THREAD

**Issue by bastians** [derhansen/sf_banners#194]
I have implemented sf_banners through TypoScript to my side but no banners are shown in the frontend.

This is my TS:
```
lib.modul.bannertop < plugin.tx_sfbanners.widgets.bannerWidget
lib.modul.bannertop.settings {
    displayMode = allRandom
    startingPoint = 99
}
```
and
```
<div id="banner">
        <f:cObject typoscriptObjectPath="lib.modul.bannertop" />
</div>
```

And this is the output:
```
<div id="banner">
    <div class="tx-sf-banners">

        <script type="text/javascript">
            if (typeof banners == "undefined")
                var banners = [];
            banners.push(['banners-mmi4mdqzy', '/de/aktuelles/?type=9001&tx_sfbanners_pi1%5Baction%5D=getBanners&tx_sfbanners_pi1%5Bcontroller%5D=Banner&tx_sfbanners_pi1%5BcurrentPageUid%5D=787&tx_sfbanners_pi1%5Bhmac%5D=88538a2f2580056f06ff098b96226a4cf67b1df5&tx_sfbanners_pi1%5BstartingPoint%5D=99&tx_sfbanners_pi1%5Bcategories%5D=&tx_sfbanners_pi1%5BdisplayMode%5D=allRandom&cHash=f54bb05897cb09eae3e0613acfc8ab83'])
        </script>
        <div id="banners-mmi4mdqzy"></div>

    </div>
</div>
```

What is strange: When I add this to my domain `/de/aktuelles/?type=9001&tx_sfbanners_pi1%5Baction%5D=getBanners&tx_sfbanners_pi1%5Bcontroller%5D=Banner&tx_sfbanners_pi1%5BcurrentPageUid%5D=787&tx_sfbanners_pi1%5Bhmac%5D=88538a2f2580056f06ff098b96226a4cf67b1df5&tx_sfbanners_pi1%5BstartingPoint%5D=99&tx_sfbanners_pi1%5Bcategories%5D=&tx_sfbanners_pi1%5BdisplayMode%5D=allRandom&cHash=f54bb05897cb09eae3e0613acfc8ab83`, I see all banners on a white page.

The only difference I see, is that the URL contains the `/de/`, but I actually I don't show the sys language in my paths.

Is this a bug or a wrong configuration?

TYPO3 v7.6.32
sf_banners v3.0.1

**Comment by derhansen** [comment]
Can you check, if the required JQuery libs are included in your frontend output?

Example: 
```
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js" type="text/javascript"></script>
<script src="/typo3conf/ext/sf_banners/Resources/Public/Js/Postscribe.js?1489254324" type="text/javascript"></script>
<script src="/typo3conf/ext/sf_banners/Resources/Public/Js/SfBanners.js?1489254324" type="text/javascript"></script>
```

**Comment by bastians** [comment]
![Untitled](https://media.giphy.com/media/ADr35Z4TvATIc/source.gif)

The most obvious thing I did not check... Sorry that I waisted your time.

In my template I am cleaning the JS implementation by third party extensions with this TS:

```
### JavaScript files implementation
page.includeJSlibs >
page.includeJS >
page.includeJSFooterlibs >
page.includeJSFooter >
```

I commented it out, now it works. 

Would you recommend to clean the JS implementation and add JS manually?

**Comment by derhansen** [comment]
In projects I manage I always use `page.include*` to make my own JS/CSS includes and also to override includes from 3rd party extensions, if I do not need the include (e.g. old version of JQuery).

But I would recommend to keep extension includes and look at the includes individually, because some extension do not work without (e.g. this one or e.g. powermail_cond).
