### ISSUE TITLE
After update with composer banners are disappeared

### ISSUE THREAD

**Issue by Balindil** [derhansen/sf_banners#195]
I already used this extension in TYPO3 9.5 and everything worked fine. After an update of the installation with the Composer the banners are no longer displayed. But the impressions will be counted further.

Version are TYPO3 9.5.5, sf_banners 4.0.2

The static template is included as well as the js files.

The source code contains the following code instead of the banner:
```html
<div id="c1609" class="frame frame-default frame-type-list frame-layout-0">
<div class="tx-sf-banners">
<script type="text/javascript">
        if (typeof banners == "undefined")
            var banners = [];
        banners.push(['banners-nziyndzin', '/?tx_sfbanners_pi1%5Baction%5D=getBanners&tx_sfbanners_pi1%5Bcategories%5D=8&tx_sfbanners_pi1%5Bcontroller%5D=Banner&tx_sfbanners_pi1%5BcurrentPageUid%5D=1&tx_sfbanners_pi1%5BdisplayMode%5D=all&tx_sfbanners_pi1%5Bhmac%5D=ebe99231280790ec2408a2289cf875600e6b3aed&tx_sfbanners_pi1%5BstartingPoint%5D=144&cHash=31ae8189dd8b8638f8b915afcef3f582'])
    </script>
<div id="banners-nziyndzin"></div>
</div>
</div>
```
There are no error messages in the console output.

**Comment by derhansen** [comment]
When the impression count is increased, the AJAX request is executed. Can you check the Browser Console for the Network Request `/?tx_sfbanners_pi1%5Baction%5D=getBanners&tx_sfbanners_pi1%5Bcategories%5D=8&tx_sfbanners_pi1%5Bcontroller%5D=Banner&tx_sfbanners_pi1%5BcurrentPageUid%5D=1&tx_sfbanners_pi1%5BdisplayMode%5D=all&tx_sfbanners_pi1%5Bhmac%5D=ebe99231280790ec2408a2289cf875600e6b3aed&tx_sfbanners_pi1%5BstartingPoint%5D=144&cHash=31ae8189dd8b8638f8b915afcef3f582`

What exactly (Response Code, Content) does this request return?

**Comment by Balindil** [comment]
That's weird. When I try this, the response code is 200 and the banners are displayed.

**Comment by Balindil** [comment]
Is there anything new here? I can still only see the banners if I call this URL directly:
www.domain.com/?tx_sfbanners_pi1%5Baction%5D=getBanners&...

Otherwise they will not be displayed!

**Comment by derhansen** [comment]
When the request returns the expected banners, then there must be something wrong with the JavaScript on your site. Since I can't reproduce the problem, there is currently nothing I can do here.

Just to make sure: Did you disable your own Ad-Blocker for the Website where `sf_banners` is used?

**Comment by Balindil** [comment]
Yes, adblockers are disabled. I haven't changed anything about javascript. Only the update made. Before everything worked fine.

**Comment by derhansen** [comment]
Sorry, I can't really help here more further information. Please provide a link to the site, where banners are not displayed, so I can have a look at the page source.

**Comment by Balindil** [comment]
[Link to site](http://kardionet.demo2.dp-medsystems.de/)

**Comment by derhansen** [comment]
The response from the AJAX Request returns the whole HTML content of the site and not just the rendered Banners. Reason is, because there is no `typeNum` parameter in URLs generated by `sf_banners`.

Please check your TypoScript (constants/setup) if the `ajaxPageTypeNum` is configured properly. You may have forgotten to include the constants of the extension.

Calling the AJAX link with the default `typeNum` results in the expected output (only banners get rendered):

http://kardionet.demo2.dp-medsystems.de/?tx_sfbanners_pi1%5Baction%5D=getBanners&tx_sfbanners_pi1%5Bcategories%5D=8&tx_sfbanners_pi1%5Bcontroller%5D=Banner&tx_sfbanners_pi1%5BcurrentPageUid%5D=1&tx_sfbanners_pi1%5BdisplayMode%5D=all&tx_sfbanners_pi1%5Bhmac%5D=ebe99231280790ec2408a2289cf875600e6b3aed&tx_sfbanners_pi1%5BstartingPoint%5D=144&cHash=31ae8189dd8b8638f8b915afcef3f582&type=9001

**Comment by Balindil** [comment]
Static typoscript is included:
![grafik](https://user-images.githubusercontent.com/6592711/57698907-06cf6c00-7657-11e9-936f-dd8d174d05f0.png)


These are the constants:
![grafik](https://user-images.githubusercontent.com/6592711/57698784-b1935a80-7656-11e9-8f68-6e93c20e3712.png)

From Typoscript Object Browser:
![grafik](https://user-images.githubusercontent.com/6592711/57699272-adb40800-7657-11e9-98de-e454a7ec2d4e.png)

As I said, everything was fine before the update.

**Comment by derhansen** [comment]
I still do not think your problem has directly something to do with the update of ext:sf_banners.

One other thing you could check is your route config. If you have configured the `PageType` route enhancer, you must make sure, that the pageTypes `9001` and `9002` are mapped. If this is not configured, then the the pageTypes of `sf_banners` are just ignored (what is the case on your website)

Example:

```
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    suffix: /
    map:
      /: 0
      banners.html: 9001
      bannerclick.html: 9002
```

If this solves your problem, please give me feedback and I will update the FAQ section in the documentation.

**Comment by Balindil** [comment]
I did not update ext:sf_banners, but TYPO3. Now the problem is clear: the new routing. I adjusted the config.yaml accordingly and now everything works again. Many thanks for your help!

**Comment by derhansen** [comment]
Link to homepage has been removed and I updated the documentation.
