### ISSUE TITLE
Question: how to view and export statistics?

### ISSUE THREAD

**Issue by roel018** [derhansen/sf_banners#197]
Hi!

I know one can simply go into each banner's back-end record and check the impressions and clicks values... BUT, when I try to export the backend table listing as a CSV, there's no way to include these fields because they are disabled in the TCA. 

So, my question is, is there a way to export the statistics so they can be compared, e.g. through a CSV file? Or are there any other ways to get an overview of the statistics, other than going into each banner separately?

Thanks!

**Comment by derhansen** [comment]
The statistics fields are declared as `none` Type in the TCA (see https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/None.html)

This must be done, so a banner can be edited in the backend while clicks/impressions are counted in the frontend. If the field was declared as input with readOnly, a backend editor could overwrite click count and impressions with old data. 

So in TYPO3, there is no direct way to quickly export the data. If you have direct access to the database (e.g. using ext:adminer or ext:phpmyadmin), you could select required data using the following SQL statement

```
SELECT uid, pid, title, clicks, impressions FROM `tx_sfbanners_domain_model_banner`
```
