### ISSUE TITLE
No link rendered for image banner

### ISSUE THREAD

**Issue by piotrburda** [derhansen/sf_banners#210]
TYPO3 7.6.32 sf_banners 3.0.1 whet using image banner image is rendered but no link. Link field in BE is filled with external and also internal link. Example of rendered code:
<//div id="banners-ywuzndk4m">
    <//div class="banner banner-2"> 
        <//img src="/uploads/tx_sfbanners/maly.jpg" alt="" width="750" height="200">
    <///div>
<///div>

**Comment by derhansen** [comment]
There are no known bugs regarding links in the version you use, so I suggest you check either your templates or the extension settings in regards to FAL (see https://github.com/derhansen/sf_banners/releases/tag/3.0.0)

Also, I do not support version 3.x any more, so I'm closing the issue.
