### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by markussoeth** [derhansen/sf_banners#238]
Sorting of banneritems from folder is not respected in output. 

Sorting in Frontend is by UID and can't be changed.

Sorting in folder in backend
![grafik](https://user-images.githubusercontent.com/306641/208932129-ada08baa-bfcd-4f9e-ba5c-e6e741e2ad37.png)

Sorting in frontend
![grafik](https://user-images.githubusercontent.com/306641/208931923-2b31b6d1-cbd8-4751-843e-1e6d4664faef.png)

**Comment by derhansen** [comment]
Thanks for your report. I can however not reproduce the problem. The default sorting of the Extbase repository is by TYPO3s `sorting` column and there is even a functional test which verifies that the configured sorting works as expected.

Can you provide some more information on how to reproduce the problem?

**Comment by markussoeth** [comment]
thank you for your response.
I have to apologize! Installled the extension in a fresh system. 
Everything works like expected.
Seems the problem is in my templates.

**Comment by markussoeth** [comment]
@derhansen : We found the problem and the solution. 
On a page with multiple instances of the plugin was one instance with the output selection "All banners random".
This caused the problem in the sorting of the banners of the other instance.
