### ISSUE TITLE
Strange sf_banners backend cache setting forcing some errors in the backend

### ISSUE THREAD

**Issue by bastians** [derhansen/sf_banners#251]
I know that v.4.0.3 is out of support but I have an issue since a few days after updating some another extension (`rn_base`). I am getting the following error in the backend:

```
Oops, an error occurred!
Class '\Sys25\RnBase\Utility\TYPO3\CMS\Core\Cache\Backend\Typo3DatabaseBackend' not found
```

The logs are showing the following:
```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: 
Class '\Sys25\RnBase\Utility\TYPO3\CMS\Core\Cache\Backend\Typo3DatabaseBackend' not found | Error thrown in file /www/htdocs/XXX/www/cms/typo3/testing/typo3/sysext/core/Classes/Cache/CacheManager.php in line 305
```

Also, when I want to delete the cache from the backend I am getting this error:
<img width="625" alt="Bildschirmfoto 2023-09-22 um 21 59 38" src="https://github.com/derhansen/sf_banners/assets/863722/21af2bf2-7c4b-4fb7-9fe2-7d6271965c76">

After a look in "$GLOBALS['TYPO3_CONF_VARS']" and the configured caches at ['SYS']['caching']['cacheConfigurations']. which extension is using the class `\Sys25\RnBase\Utility\TYPO3\CMS\Core\Cache\Backend\Typo3DatabaseBackend`I found out that `sf_banners` it is:

<img width="657" alt="Bildschirmfoto 2023-09-25 um 19 55 44" src="https://github.com/derhansen/sf_banners/assets/863722/4e5ad1b5-9fc3-4fd5-b940-de3d49f73968">

I have no clue why and therefore I hope finding some help here how to solve it :)

**Comment by derhansen** [comment]
See here: https://github.com/derhansen/sf_banners/blob/4.x/ext_localconf.php#L27

It seems the missing slash (`...['backend'] = TYPO3...` should most likely be `...['backend'] = \TYPO3...`) before the cache definition seems to make problems. Please adjust/fix this yourself in the code of the extension, since I will not provide any updates for this version any more.

**Comment by bastians** [comment]
Awesome, thanks for the hint and fast support :)
