### ISSUE TITLE
Sorting in backend throws PHP warning

### ISSUE THREAD

**Issue by stephaniestief** [derhansen/sf_banners#253]
If you want to sort the banners with the arrows in the list module in the backend, the following error appears:

PHP Warning: Undefined array key "t3ver_label" in vendor/typo3/cms-core/Classes/DataHandling/DataHandler.php line 8753

After reloading the page, the new sorting is applied.

Affected versions:
- TYPO3 12.4.8
- PHP 8.2.8
- sf_banners 7.0.1
- Composer Installation

**Comment by derhansen** [comment]
Fixed in version 6.0.4 and 7.0.2, which have just been released.

**Comment by stephaniestief** [comment]
Wow, thank you for the quick fix! Amazing :)
